[pyprland]
plugins = [
    "wallpapers"
]

[wallpapers]
path=["/media/share/linux/wallpapers"]
unique = true
command = '/usr/local/bin/hyprctl hyprpaper wallpaper "[output],[file],contain"'
clear_command = '/usr/local/bin/hyprctl hyprpaper unload all'
interval = 42
